name: Pull Request
on:
  pull_request:

jobs:
  pull-request-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: marshmallow-insurance/campfire/.github/actions/setup-node-project@main
      - name: Run Check Types
        run: npm run check-types
      - name: Run Tests
        run: npm run test
      - name: Run Build Storybook
        run: |
          npm run build-storybook --quiet
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Serve Storybook and test
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && npm run test-storybook:ci"
